In [1]:
import numpy as np

# Numpy Init

In [2]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
np.ones((3, 5), dtype=bool)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Numpy Boolean

In [4]:
a = np.array([True, True, False, False])
b = np.array([True, False, True, False])

In [5]:
# and
print(a & b)

# or
print(a | b)

[ True False False False]
[ True  True  True False]


In [8]:
# and
print(np.logical_and(a, b))

# or
print(np.logical_or(a, b))

# xor
print(np.logical_xor(a, b))

# not
print(np.logical_not(a))

[ True False False False]
[ True  True  True False]
[False  True  True False]
[False False  True  True]


# Numpy Append

In [15]:
np.empty((0, 5))

array([], shape=(0, 5), dtype=float64)

In [12]:
data = np.empty((0, 5))
# 추가 array는 다중 배열!
# 행 추가시 axis = 0
data = np.append(data, np.array([[1, 1, 1, 1, 1]]), axis = 0)
data = np.append(data, np.array([[2, 2, 2, 2, 2]]), axis = 0)

In [13]:
print(data)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]]


# Numpy data Type 변환

In [31]:
data = np.empty((0, 4))
data = np.append(data, np.array([['str2', 'True', '22', '0.33']]), axis = 0)
data = np.append(data, np.array([['str3', 'False', '44', '0.44']]), axis = 0)
data = np.append(data, np.array([['str4', 'True', '55', '0.66']]), axis = 0)

In [32]:
print(data)

[['str2' 'True' '22' '0.33']
 ['str3' 'False' '44' '0.44']
 ['str4' 'True' '55' '0.66']]


In [55]:
a = data[:,0].astype(np.object)
b = data[:,2].astype(np.int32)
c = data[:,3].astype(np.float32)

In [60]:
type(a[0])

str

In [62]:
type(b[0])

numpy.int32

In [63]:
type(c[0])

numpy.float32

In [86]:
d = data[:,1] == np.ones((data[:,1].shape), dtype=bool).astype(np.unicode)

In [90]:
type(d[0])

numpy.bool_

# Python - TypeError - Object of type ‘int64’ is not JSON serializable
> json 파일로 저장시 데이터 타입이 int64가 포함되어 있어 저장이 불가능하다는 오류

In [24]:
# 일반 리스트 데이터에서의 숫자 타입은 int형
integer_lst = [1, 2, 3]
print(integer_lst)
print(type(integer_lst[0]))

[1, 2, 3]
<class 'int'>


In [25]:
# numpy 숫자 타입은 int** 형
np_int_lst = np.array(integer_lst)
print(type(np_int_lst[0]))

<class 'numpy.int32'>


In [26]:
import json

In [27]:
# 리스트 형태로 바꾸어도 그대로 유지됨
# json 파일로 저장 시 에러 발생!!
# kakao coding test 시 에러 발생하였음

np_int_lst = list(np_int_lst)
print(type(np_int_lst[0]))

with open("temp.json", 'w') as f: 
    json.dump(list(np_int_lst), f)

<class 'numpy.int32'>


TypeError: Object of type int32 is not JSON serializable

In [28]:
# 데이터 타입을 int 형태로 바꾸면  json 파일로 저장 가능!
np_int_lst = list([int(x) for x in np_int_lst])
print(type(np_int_lst[0]))

with open("temp.json", 'w') as f: 
    json.dump(list(np_int_lst), f)

<class 'int'>
